version: "3" 
services: 
 proxy-container: 
   build:
    context: .
    dockerfile: Dockerfile
   command: bash -c "cd code && npm i && npm run dev"
   ports: 
    - "3000:3000" 
   stdin_open: true 
   tty: true 
   volumes: 
     - ./:/code